author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Component::AI::MegaHAL
name: POE-Component-AI-MegaHAL
no_index:
  directory:
    - inc
    - t
requires:
  AI::MegaHAL: 0.04
  Carp: 0
  POE: 0.31
version: 1.03
