---
abstract: 'A non-blocking wrapper around AI::MegaHAL.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-AI-MegaHAL
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  AI::MegaHAL: 0.07
  POE: 0.9999
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.16
