author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-AI-MegaHAL
no_index: 
  directory: 
    - inc
    - t
requires: 
  AI::MegaHAL: 0.05
  Carp: 0
  POE: 0.38
version: 1.05
